name: Android CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Access API_KEY
      run: |
        echo UNIVCERT_API_KEY=\"$UNIVCERT_API_KEY\" >> local.properties
        echo KAKAO_APP_KEY=$KAKAO_APP_KEY >> local.properties
      env:
        KAKAO_APP_KEY: ${{secrets.KAKAO_APP_KEY }}
        UNIVCERT_API_KEY: ${{secrets.UNIVCERT_API_KEY }}
    - name: create-json
      id: create-json-1
      uses: jsdaniell/create-json@v1.2.2
      with:
        name: "google-services.json"
        json: ${{ secrets.GOOGLE_SERVICE }}
        dir: 'app/'
    - name: Build with Gradle
      run: bash ./gradlew assembleDebug --stacktrace
