name: Android CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Access UNIVCERT_API_KEY
      run: |
        echo UNIVCERT_API_KEY=\"$UNIVCERT_API_KEY\" > local.properties
      env:
        API_KEY: ${{secrets.UNIVCERT_API_KEY }}
    - name: Build with Gradle
      run: ./gradlew build
